[package]
description = "CosmWasm integration testing for Neutron"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "neutron-test-tube"
repository = "https://github.com/j0nl1/neutron-test-tube"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["neutron", "test_artifacts"]

[dependencies]
base64 = "0.21.5"
cosmrs = { version = "0.15.0", features = ["cosmwasm"] }
cosmwasm-std = "1.5"
neutron-sdk = { package = "astroport-neutron-sdk", git = "https://github.com/epanchee/neutron-sdk", branch = "backport/cosmwasm_v1", version = "0.11.0-cosmwasm-v1" }
prost = "0.12.3"
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = { version = "0.5.0", path = "../test-tube" }
thiserror = "1.0.34"

[features]
default = []
wasm-sudo = []

[build-dependencies]
bindgen = "0.69.1"

[dev-dependencies]
cw1-whitelist = "1.1.1"
rayon = "1.5.3"
